package Server.model.game.fields;

public enum CardFieldType {
    PLAYER_DECK,
    PLAYER_HAND,
    PLAYER_FIELD_ZONE,
    PLAYER_GRAVEYARD,
    PLAYER_MONSTER,
    PLAYER_SPELL_TRAP,
    OPPONENT_DECK,
    OPPONENT_HAND,
    OPPONENT_FIELD_ZONE,
    OPPONENT_GRAVEYARD,
    OPPONENT_MONSTER,
    OPPONENT_SPELL_TRAP
}
