package model.card;

public enum SpecialMonsterEnum {
    BEAST_KING_BARBAROS,
    THE_TRICKY,
    SKULL_GUARDIAN,
    EXPLODER_DRAGON,
    THE_CALCULATOR,
    HERALD_OF_CREATION,
    SCANNER,
    COMMAND_KNIGHT,
    SUIJIN,
    MAN_EATER_BUG,
    MARSHMALLON,
    MIRAGE_DRAGON,
    TEXCHANGER,
    GATE_GUARDIAN,
    CRAB_TURTLE,
    TERRATIGER,
    YOMI_SHIP;
}
